// spotsData.js
export const spotsData = {
  "zh-tw": [
    { name: "歡迎來到十鼓文創園區", url: "1/zh-tw" },
    { name: "糖鐵軌道與糖業趣聞", url: "2/zh-tw" },
    { name: "十鼓餐廳-五分車廂", url: "3/zh-tw" },
    { name: "煙囱", url: "4/zh-tw" },
    { name: "煙囱內部", url: "5/zh-tw" },
    { name: "糖Bar子-砂糖打包區", url: "6/zh-tw" },
    { name: "魔法工廠", url: "7/zh-tw" },
    { name: "上帝的畫作~大自然的活畫布", url: "8/zh-tw" },
    { name: "糖蜜三連罐-獸骨祭壇", url: "9/zh-tw" },
    { name: "糖蜜三連罐-兒童體驗館", url: "10/zh-tw" },
    { name: "糖蜜三連罐-鼓波咖啡", url: "11/zh-tw" },
    { name: "魔法帽涼亭＆甜蜜之丘", url: "12/zh-tw" },
    { name: "齒輪舞台", url: "13/zh-tw" },
    { name: "車路墘故事館", url: "14/zh-tw" },
    { name: "清溪林製鼓廠", url: "15/zh-tw" },
    { name: "甘蔗廁所", url: "16/zh-tw" },
    { name: "魔法彩虹街", url: "17/zh-tw" },
    { name: "生命之樹-天空步道", url: "18/zh-tw" },
    { name: "魔域王座", url: "19/zh-tw" },
    { name: "夢糖劇場-五重壓榨機", url: "20/zh-tw" },
    { name: "修護書屋", url: "21/zh-tw" },
    { name: "撐篙划船區", url: "22/zh-tw" },
    { name: "結晶罐～銀河糖晶扭蛋機", url: "23/zh-tw" },
    { name: "攪拌器～室內射箭場", url: "24/zh-tw" },
    { name: "天井紅屋＆火車頭", url: "25/zh-tw" },
    { name: "天堂上的鞦韆", url: "26/zh-tw" },
    { name: "糖箱區-鋼鐵鐳戰", url: "27/zh-tw" },
    { name: "一粒糖的旅行", url: "28/zh-tw" },
    { name: "祈福館～黃帝殿", url: "29/zh-tw" }
  ],
  "en": [
    { name: "Welcome to Ten Drum Cultural and Creative Park", url: "1/en" },
    { name: "Sugar Railway Tracks & Sugar Industry Trivia", url: "2/en" },
    { name: "Ten Drum Restaurant - Five-Cent Carriages", url: "3/en" },
    { name: "Chimney", url: "4/en" },
    { name: "Inside the Chimney", url: "5/en" },
    { name: "Sugar Bar - Sugar Packing Area", url: "6/en" },
    { name: "Magic Factory", url: "7/en" },
    { name: "God's Painting ~ Nature's Living Canvas", url: "8/en" },
    { name: "Molasses Tanks - Beast Bone Altar", url: "9/en" },
    { name: "Molasses Tanks - Children's Experience Hall", url: "10/en" },
    { name: "Molasses Tanks - Drum Wave Cafe", url: "11/en" },
    { name: "Magic Hat Pavilion & Sweet Hill", url: "12/en" },
    { name: "Gear Stage", url: "13/en" },
    { name: "Cheluqian Story House", url: "14/en" },
    { name: "Qingxilin Drum Factory", url: "15/en" },
    { name: "Sugarcane Restroom", url: "16/en" },
    { name: "Magic Rainbow Street", url: "17/en" },
    { name: "Tree of Life - Skywalk", url: "18/en" },
    { name: "Throne of the Magic Realm", url: "19/en" },
    { name: "Dream Sugar Theatre - Five-Stage Crusher", url: "20/en" },
    { name: "Repair Book House", url: "21/en" },
    { name: "Punting Boat Area", url: "22/en" },
    { name: "Crystallization Tank ~ Milky Way Sugar Crystal Gashapon Machine", url: "23/en" },
    { name: "Mixer ~ Indoor Archery Range", url: "24/en" },
    { name: "Patio Red House & Locomotive", url: "25/en" },
    { name: "Swing on Heaven", url: "26/en" },
    { name: "Sugar Box Area - Steel Laser Battle", url: "27/en" },
    { name: "A Grain of Sugar's Journey", url: "28/en" },
    { name: "Blessing Hall ~ Huangdi Temple", url: "29/en" }
  ],
  "ja": [
    { name: "十鼓文創園区へようこそ", url: "1/ja" },
    { name: "糖鉄軌道と砂糖産業のトリビア", url: "2/ja" },
    { name: "十鼓レストラン - トロッコ車両", url: "3/ja" },
    { name: "煙突", url: "4/ja" },
    { name: "煙突内部", url: "5/ja" },
    { name: "シュガーBar - 砂糖パッキングエリア", url: "6/ja" },
    { name: "魔法工場", url: "7/ja" },
    { name: "神様の絵画〜大自然の生きたキャンバス", url: "8/ja" },
    { name: "糖蜜タンク - 獣骨の祭壇", url: "9/ja" },
    { name: "糖蜜タンク - キッズ体験館", url: "10/ja" },
    { name: "糖蜜タンク - 鼓波カフェ", url: "11/ja" },
    { name: "魔法の帽子東屋＆スウィートヒル", url: "12/ja" },
    { name: "ギアステージ", url: "13/ja" },
    { name: "車路墘ストーリーハウス", url: "14/ja" },
    { name: "清渓林製太鼓工場", url: "15/ja" },
    { name: "サトウキビトイレ", url: "16/ja" },
    { name: "魔法のレインボーストリート", url: "17/ja" },
    { name: "生命の樹 - スカイウォーク", url: "18/ja" },
    { name: "魔域の玉座", url: "19/ja" },
    { name: "夢糖劇場 - 五重圧搾機", url: "20/ja" },
    { name: "修繕ブックハウス", url: "21/ja" },
    { name: "竿さし舟エリア", url: "22/ja" },
    { name: "結晶タンク〜天の川シュガークリスタルガチャガチャ", url: "23/ja" },
    { name: "ミキサー〜屋内アーチェリー場", url: "24/ja" },
    { name: "吹き抜け赤レンガ館＆機関車", url: "25/ja" },
    { name: "天国のブランコ", url: "26/ja" },
    { name: "砂糖箱エリア - スチールレーザータグ", url: "27/ja" },
    { name: "一粒の砂糖の旅", url: "28/ja" },
    { name: "祈福館〜黄帝殿", url: "29/ja" }
  ],
  "ko": [
    { name: "십고 문화창의구역에 오신 것을 환영합니다", url: "1/ko" },
    { name: "설탕 철도와 설탕 산업 이야기", url: "2/ko" },
    { name: "십고 레스토랑 - 오분차 객차", url: "3/ko" },
    { name: "굴뚝", url: "4/ko" },
    { name: "굴뚝 내부", url: "5/ko" },
    { name: "설탕 Bar - 설탕 포장 구역", url: "6/ko" },
    { name: "마법 공장", url: "7/ko" },
    { name: "신의 그림 ~ 대자연의 살아있는 화폭", url: "8/ko" },
    { name: "당밀 탱크 - 짐승 뼈 제단", url: "9/ko" },
    { name: "당밀 탱크 - 어린이 체험관", url: "10/ko" },
    { name: "당밀 탱크 - 고파 카페", url: "11/ko" },
    { name: "마법 모자 원두막 & 스위트 힐", url: "12/ko" },
    { name: "톱니바퀴 무대", url: "13/ko" },
    { name: "차로건 스토리 하우스", url: "14/ko" },
    { name: "청계림 북 제작 공장", url: "15/ko" },
    { name: "사탕수수 화장실", url: "16/ko" },
    { name: "마법 무지개 거리", url: "17/ko" },
    { name: "생명의 나무 - 스카이워크", url: "18/ko" },
    { name: "마역 왕좌", url: "19/ko" },
    { name: "꿈의 설탕 극장 - 5중 압착기", url: "20/ko" },
    { name: "수리 서점", url: "21/ko" },
    { name: "장대 노젓기 배 체험구역", url: "22/ko" },
    { name: "결정 탱크 ~ 은하 설탕 결정 캡슐 뽑기", url: "23/ko" },
    { name: "교반기 ~ 실내 양궁장", url: "24/ko" },
    { name: "중정 레드 하우스 & 기관차", url: "25/ko" },
    { name: "천국 위의 그네", url: "26/ko" },
    { name: "설탕 상자 구역 - 스틸 레이저 서바이벌", url: "27/ko" },
    { name: "한 알의 설탕의 여행", url: "28/ko" },
    { name: "기원관 ~ 황제전", url: "29/ko" }
  ],
  "vi": [
    { name: "Chào mừng đến với Khu Sáng tạo Văn hóa Ten Drum", url: "1/vi" },
    { name: "Đường ray tàu đường & Chuyện thú vị ngành đường", url: "2/vi" },
    { name: "Nhà hàng Ten Drum - Toa tàu 5 phân", url: "3/vi" },
    { name: "Ống khói", url: "4/vi" },
    { name: "Bên trong ống khói", url: "5/vi" },
    { name: "Sugar Bar - Khu đóng gói đường", url: "6/vi" },
    { name: "Nhà máy Phép thuật", url: "7/vi" },
    { name: "Tuyệt tác của Chúa ~ Bức tranh sống động của thiên nhiên", url: "8/vi" },
    { name: "Bồn chứa mật đường - Bàn thờ xương thú", url: "9/vi" },
    { name: "Bồn chứa mật đường - Nhà trải nghiệm trẻ em", url: "10/vi" },
    { name: "Bồn chứa mật đường - Cà phê Cổ Ba", url: "11/vi" },
    { name: "Chòi Mũ Phép thuật & Ngọn đồi Ngọt ngào", url: "12/vi" },
    { name: "Sân khấu Bánh răng", url: "13/vi" },
    { name: "Nhà câu chuyện Xa Lộ Kiền", url: "14/vi" },
    { name: "Xưởng làm trống Thanh Khê Lâm", url: "15/vi" },
    { name: "Nhà vệ sinh Cây mía", url: "16/vi" },
    { name: "Phố Cầu vồng Phép thuật", url: "17/vi" },
    { name: "Cây Cứu rỗi - Cầu trên cao", url: "18/vi" },
    { name: "Ngai vàng Ma giới", url: "19/vi" },
    { name: "Nhà hát Mộng Đường - Máy ép 5 tầng", url: "20/vi" },
    { name: "Tiệm sách Sửa chữa", url: "21/vi" },
    { name: "Khu chèo thuyền chống sào", url: "22/vi" },
    { name: "Bồn tinh thể ~ Máy vặn trứng tinh thể đường Ngân Hà", url: "23/vi" },
    { name: "Máy trộn ~ Sân bắn cung trong nhà", url: "24/vi" },
    { name: "Nhà đỏ Giếng trời & Đầu máy xe lửa", url: "25/vi" },
    { name: "Xích đu trên Thiên đường", url: "26/vi" },
    { name: "Khu hộp đường - Bắn súng laser thép", url: "27/vi" },
    { name: "Hành trình của một hạt đường", url: "28/vi" },
    { name: "Đền Cầu an ~ Hoàng Đế Điện", url: "29/vi" }
  ],
  "id": [
    { name: "Selamat Datang di Taman Kreatif dan Budaya Ten Drum", url: "1/id" },
    { name: "Rel Kereta Gula & Trivia Industri Gula", url: "2/id" },
    { name: "Restoran Ten Drum - Gerbong Kereta Lima Persen", url: "3/id" },
    { name: "Cerobong Asap", url: "4/id" },
    { name: "Bagian Dalam Cerobong Asap", url: "5/id" },
    { name: "Sugar Bar - Area Pengemasan Gula", url: "6/id" },
    { name: "Pabrik Sihir", url: "7/id" },
    { name: "Lukisan Tuhan ~ Kanvas Hidup Alam", url: "8/id" },
    { name: "Tangki Tetes Tebu - Altar Tulang Binatang", url: "9/id" },
    { name: "Tangki Tetes Tebu - Wahana Pengalaman Anak", url: "10/id" },
    { name: "Tangki Tetes Tebu - Kafe Gubo", url: "11/id" },
    { name: "Saung Topi Sihir & Bukit Manis", url: "12/id" },
    { name: "Panggung Roda Gigi", url: "13/id" },
    { name: "Rumah Cerita Cheluqian", url: "14/id" },
    { name: "Pabrik Pembuatan Drum Qingxilin", url: "15/id" },
    { name: "Toilet Tebu", url: "16/id" },
    { name: "Jalan Pelangi Sihir", url: "17/id" },
    { name: "Pohon Kehidupan - Jembatan Gantung Skywalk", url: "18/id" },
    { name: "Tahta Dunia Sihir", url: "19/id" },
    { name: "Teater Impian Gula - Mesin Pemeras 5 Tingkat", url: "20/id" },
    { name: "Rumah Buku Perbaikan", url: "21/id" },
    { name: "Area Naik Perahu Dayung", url: "22/id" },
    { name: "Tangki Kristalisasi ~ Mesin Gashapon Kristal Gula Bima Sakti", url: "23/id" },
    { name: "Pengaduk ~ Arena Panahan Dalam Ruangan", url: "24/id" },
    { name: "Rumah Merah Atap Terbuka & Lokomotif", url: "25/id" },
    { name: "Aunan di Surga", url: "26/id" },
    { name: "Area Kotak Gula - Pertempuran Laser Baja", url: "27/id" },
    { name: "Perjalanan Sebutir Gula", url: "28/id" },
    { name: "Aula Doa ~ Kuil Huangdi", url: "29/id" }
  ],
  "th": [
    { name: "ยินดีต้อนรับสู่สวนสร้างสรรค์วัฒนธรรม Ten Drum", url: "1/th" },
    { name: "ทางรถไฟน้ำตาลและเรื่องน่ารู้ของอุตสาหกรรมน้ำตาล", url: "2/th" },
    { name: "ร้านอาหาร Ten Drum - โบกี้รถไฟห้าส่วน", url: "3/th" },
    { name: "ปล่องไฟ", url: "4/th" },
    { name: "ภายในปล่องไฟ", url: "5/th" },
    { name: "Sugar Bar - พื้นที่บรรจุน้ำตาล", url: "6/th" },
    { name: "โรงงานเวทมนตร์", url: "7/th" },
    { name: "ภาพเขียนของพระเจ้า ~ ผืนผ้าใบมีชีวิตแห่งธรรมชาติ", url: "8/th" },
    { name: "ถังหมักน้ำตาล - แท่นบูชากระดูกสัตว์", url: "9/th" },
    { name: "ถังหมักน้ำตาล - ศาลาประสบการณ์เด็ก", url: "10/th" },
    { name: "ถังหมักน้ำตาล - กาแฟกู่โป", url: "11/th" },
    { name: "ศาลาหมวกเวทมนตร์ & เนินเขาแห่งความหวาน", url: "12/th" },
    { name: "เวทีฟันเฟือง", url: "13/th" },
    { name: "เรือนเรื่องเล่าเฉอลู่เชียน", url: "14/th" },
    { name: "โรงงานทำกลองชิงซีหลิน", url: "15/th" },
    { name: "ห้องน้ำต้นอ้อย", url: "16/th" },
    { name: "ถนนสายรุ้งเวทมนตร์", url: "17/th" },
    { name: "ต้นไม้แห่งชีวิต - ทางเดินลอยฟ้า", url: "18/th" },
    { name: "บัลลังก์แดนเวทมนตร์", url: "19/th" },
    { name: "โรงละครความฝันน้ำตาล - เครื่องบีบอัด 5 ขั้น", url: "20/th" },
    { name: "ร้านหนังสือซ่อมบำรุง", url: "21/th" },
    { name: "โซนถ่อเรือพาย", url: "22/th" },
    { name: "ถังผลึก ~ ตู้กาชาปองผลึกน้ำตาลทางช้างเผือก", url: "23/th" },
    { name: "เครื่องผสม ~ สนามยิงธนูในร่ม", url: "24/th" },
    { name: "เรือนแดงหลังคาโปร่ง & หัวรถจักร", url: "25/th" },
    { name: "ชิงช้าบนสวรรค์", url: "26/th" },
    { name: "โซนกล่องน้ำตาล - เลเซอร์แท็กเหล็กกล้า", url: "27/th" },
    { name: "การเดินทางของน้ำตาลหนึ่งเม็ด", url: "28/th" },
    { name: "ศาลาขอพร ~ วิหารหวงตี้", url: "29/th" }
  ],
  "ms": [
    { name: "Selamat Datang ke Taman Kreatif Budaya Ten Drum", url: "1/ms" },
    { name: "Landasan Kereta Api Gula & Trivia Industri Gula", url: "2/ms" },
    { name: "Restoran Ten Drum - Gerbong Kereta Api Lima Sen", url: "3/ms" },
    { name: "Corong Asap", url: "4/ms" },
    { name: "Bahagian Dalam Corong Asap", url: "5/ms" },
    { name: "Sugar Bar - Kawasan Pembungkusan Gula", url: "6/ms" },
    { name: "Kilang Sihir", url: "7/ms" },
    { name: "Lukisan Tuhan ~ Kanvas Hidup Alam Semulajadi", url: "8/ms" },
    { name: "Tangki Molases - Altar Tulang Haiwan", url: "9/ms" },
    { name: "Tangki Molases - Dewan Pengalaman Kanak-kanak", url: "10/ms" },
    { name: "Tangki Molases - Kafe Gubo", url: "11/ms" },
    { name: "Pavilion Topi Sihir & Bukit Manis", url: "12/ms" },
    { name: "Pentas Roda Gigi", url: "13/ms" },
    { name: "Rumah Cerita Cheluqian", url: "14/ms" },
    { name: "Kilang Pembuatan Dram Qingxilin", url: "15/ms" },
    { name: "Tandas Tebu", url: "16/ms" },
    { name: "Jalan Pelangi Sihir", url: "17/ms" },
    { name: "Pohon Kehidupan - Laluan Skywalk", url: "18/ms" },
    { name: "Takhta Alam Sihir", url: "19/ms" },
    { name: "Teater Impian Gula - Mesin Pemerah 5 Peringkat", url: "20/ms" },
    { name: "Rumah Buku Pembaikan", url: "21/ms" },
    { name: "Kawasan Sampan Dayung", url: "22/ms" },
    { name: "Tangki Pengkristalan ~ Mesin Gashapon Kristal Gula Bima Sakti", url: "23/ms" },
    { name: "Pengadul ~ Lapang Sasar Memanah Dalam Bangunan", url: "24/ms" },
    { name: "Rumah Merah Bumbung Terbuka & Lokomotif", url: "25/ms" },
    { name: "Buaian di Syurga", url: "26/ms" },
    { name: "Kawasan Kotak Gula - Pertempuran Laser Keluli", url: "27/ms" },
    { name: "Perjalanan Sebutir Gula", url: "28/ms" },
    { name: "Dewan Doa ~ Kuil Huangdi", url: "29/ms" }
  ],
  "fr": [
    { name: "Bienvenue au Parc Culturel et Créatif Ten Drum", url: "1/fr" },
    { name: "Voies ferrées sucrières et anecdotes industrielles", url: "2/fr" },
    { name: "Restaurant Ten Drum - Wagons de 5 centièmes", url: "3/fr" },
    { name: "Cheminée", url: "4/fr" },
    { name: "L'intérieur de la cheminée", url: "5/fr" },
    { name: "Sugar Bar - Zone d'emballage du sucre", url: "6/fr" },
    { name: "Fabrique Magique", url: "7/fr" },
    { name: "L'œuvre de Dieu ~ Toile vivante de la nature", url: "8/fr" },
    { name: "Réservoirs de mélasse - Autel des os de bêtes", url: "9/fr" },
    { name: "Réservoirs de mélasse - Espace expérience enfants", url: "10/fr" },
    { name: "Réservoirs de mélasse - Café Gubo", url: "11/fr" },
    { name: "Kiosque du Chapeau Magique & Colline Sucrée", url: "12/fr" },
    { name: "Scène des Engrenages", url: "13/fr" },
    { name: "Maison de l'histoire de Cheluqian", url: "14/fr" },
    { name: "Fabrique de tambours Qingxilin", url: "15/fr" },
    { name: "Toilettes Canne à Sucre", url: "16/fr" },
    { name: "Rue de l'Arc-en-ciel Magique", url: "17/fr" },
    { name: "Arbre de Vie - Passerelle céleste", url: "18/fr" },
    { name: "Trône du Royaume Magique", url: "19/fr" },
    { name: "Théâtre du Sucre Rêvé - Presse à 5 niveaux", url: "20/fr" },
    { name: "Librairie de Réparation", url: "21/fr" },
    { name: "Zone de Punnage en Barque", url: "22/fr" },
    { name: "Cuve de cristallisation ~ Distributeur Gashapon de cristal de sucre", url: "23/fr" },
    { name: "Mélangeur ~ Stand de tir à l'arc couvert", url: "24/fr" },
    { name: "Maison Rouge Puits de Jour & Locomotive", url: "25/fr" },
    { name: "Balançoire du Paradis", url: "26/fr" },
    { name: "Zone des bacs à sucre - Laser Game d'Acier", url: "27/fr" },
    { name: "Le voyage d'un grain de sucre", url: "28/fr" },
    { name: "Pavillon des Vœux ~ Temple Huangdi", url: "29/fr" }
  ],
  "de": [
    { name: "Willkommen im Ten Drum Kultur- und Kreativpark", url: "1/de" },
    { name: "Zuckerbahngleise & Wissenswertes über die Zuckerindustrie", url: "2/de" },
    { name: "Ten Drum Restaurant - Waggons des Fünf-Zent-Zuges", url: "3/de" },
    { name: "Schornstein", url: "4/de" },
    { name: "Im Inneren des Schornsteins", url: "5/de" },
    { name: "Sugar Bar - Zuckerverpackungsbereich", url: "6/de" },
    { name: "Magiefabrik", url: "7/de" },
    { name: "Gottes Gemälde ~ Die lebendige Leinwand der Natur", url: "8/de" },
    { name: "Melassetanks - Altargerüst aus Tierknochen", url: "9/de" },
    { name: "Melassetanks - Erlebniswelt für Kinder", url: "10/de" },
    { name: "Melassetanks - Gubo Café", url: "11/de" },
    { name: "Zauberhut-Pavillon & Süßer Hügel", url: "12/de" },
    { name: "Zahnrad-Bühne", url: "13/de" },
    { name: "Cheluqian-Geschichtenhaus", url: "14/de" },
    { name: "Qingxilin Trommelfabrik", url: "15/de" },
    { name: "Zuckerrohr-Toiletten", url: "16/de" },
    { name: "Magische Regenbogenstraße", url: "17/de" },
    { name: "Baum des Lebens - Skywalk", url: "18/de" },
    { name: "Thron des Magischen Reiches", url: "19/de" },
    { name: "Traumzucker-Theater - 5-Stufen-Presse", url: "20/de" },
    { name: "Reparatur-Buchhandlung", url: "21/de" },
    { name: "Stakboot-Fahrbereich", url: "22/de" },
    { name: "Kristallisationsbehälter ~ Milchstraßen-Zuckerkristall-Gashapon-Automat", url: "23/de" },
    { name: "Mischer ~ Indoor-Bogenschießstand", url: "24/de" },
    { name: "Atrium Red House & Lokomotive", url: "25/de" },
    { name: "Schaukel im Himmel", url: "26/de" },
    { name: "Zuckerbehälterbereich - Stahl-Lasertag", url: "27/de" },
    { name: "Die Reise eines Zuckerkorns", url: "28/de" },
    { name: "Segenstempel ~ Huangdi-Palast", url: "29/de" }
  ],
  "es": [
    { name: "Bienvenido al Parque Cultural y Creativo Ten Drum", url: "1/es" },
    { name: "Vías del tren azucarero y curiosidades de la industria", url: "2/es" },
    { name: "Restaurante Ten Drum - Vagones de Cinco Centavos", url: "3/es" },
    { name: "Chimenea", url: "4/es" },
    { name: "Interior de la chimenea", url: "5/es" },
    { name: "Sugar Bar - Zona de empaquetado de azúcar", url: "6/es" },
    { name: "Fábrica Mágica", url: "7/es" },
    { name: "La obra de Dios ~ El lienzo vivo de la naturaleza", url: "8/es" },
    { name: "Tanques de melaza - Altar de huesos de bestias", url: "9/es" },
    { name: "Tanques de melaza - Pabellón de experiencias infantiles", url: "10/es" },
    { name: "Tanques de melaza - Café Gubo", url: "11/es" },
    { name: "Kiosco Sombrero Mágico y Colina Dulce", url: "12/es" },
    { name: "Escenario de Engranajes", url: "13/es" },
    { name: "Casa de la Historia de Cheluqian", url: "14/es" },
    { name: "Fábrica de Tambores Qingxilin", url: "15/es" },
    { name: "Baños Caña de Azúcar", url: "16/es" },
    { name: "Calle Arcoíris Mágico", url: "17/es" },
    { name: "Árbol de la Vida - Pasarela Céleste", url: "18/es" },
    { name: "Trono del Reino Mágico", url: "19/es" },
    { name: "Teatro Sueño de Azúcar - Prensa de 5 niveles", url: "20/es" },
    { name: "Librería de Reparación", url: "21/es" },
    { name: "Zona de Paseo en Barca con Pertiga", url: "22/es" },
    { name: "Tanque de cristalización ~ Máquina Gashapon de cristal de azúcar", url: "23/es" },
    { name: "Mezcladora ~ Campo de tiro con arco cubierto", url: "24/es" },
    { name: "Casa Roja Tragaluz y Locomotora", url: "25/es" },
    { name: "Columpio en el Cielo", url: "26/es" },
    { name: "Zona de contenedores de azúcar - Laser Tag de Acero", url: "27/es" },
    { name: "El viaje de un grano de azúcar", url: "28/es" },
    { name: "Pabellón de Bendiciones ~ Templo Huangdi", url: "29/es" }
  ],
  "ar": [
    { name: "مرحبًا بكم في مجمع Ten Drum الثقافي والإبداعي", url: "1/ar" },
    { name: "سكك حديد السكر ومعلومات ممتعة عن صناعة السكر", url: "2/ar" },
    { name: "مطعم Ten Drum - عربات قطار الخمسة سنتات", url: "3/ar" },
    { name: "المدخنة", url: "4/ar" },
    { name: "داخل المدخنة", url: "5/ar" },
    { name: "Sugar Bar - منطقة تعبئة السكر", url: "6/ar" },
    { name: "مصنع السحر", url: "7/ar" },
    { name: "لوحة الإله ~ لوحة الطبيعة الحية", url: "8/ar" },
    { name: "خزانات دبس السكر - مذبح عظام الحيوانات", url: "9/ar" },
    { name: "خزانات دبس السكر - قاعة تجارب الأطفال", url: "10/ar" },
    { name: "خزانات دبس السكر - مقهى غوبو", url: "11/ar" },
    { name: "جناح قبعة السحر والتل الحلو", url: "12/ar" },
    { name: "مسرح التروس", url: "13/ar" },
    { name: "بيت قصص تشيلوتشيان", url: "14/ar" },
    { name: "مصنع تشينغشيلين لصناعة الطبول", url: "15/ar" },
    { name: "حمامات قصب السكر", url: "16/ar" },
    { name: "شارع قوس قزح السحري", url: "17/ar" },
    { name: "شجرة الحياة - الممر الهوائي", url: "18/ar" },
    { name: "عرش العالم السحري", url: "19/ar" },
    { name: "مسرح أحلام السكر - معصرة من 5 مراحل", url: "20/ar" },
    { name: "مكتبة الإصلاح", url: "21/ar" },
    { name: "منطقة ركوب القوارب بالخيزران", url: "22/ar" },
    { name: "خزان التبلور ~ لعبة غاشابون بلورات سكر درب التبانة", url: "23/ar" },
    { name: "خلاط ~ ميدان الرماية بالسهم الداخلي", url: "24/ar" },
    { name: "البيت الأحمر ذو المنور والقاطرة", url: "25/ar" },
    { name: "أرجوحة السماء", url: "26/ar" },
    { name: "منطقة صناديق السكر - معركة الليزر الفولاذية", url: "27/ar" },
    { name: "رحلة حبة سكر", url: "28/ar" },
    { name: "قاعة البركات ~ معبد هوانغدي", url: "29/ar" }
  ],
  "pt": [
    { name: "Bem-vindo ao Parque Cultural e Criativo Ten Drum", url: "1/pt" },
    { name: "Trilhos do comboio do açúcar e curiosidades da indústria", url: "2/pt" },
    { name: "Restaurante Ten Drum - Vagões de Cinco Centavos", url: "3/pt" },
    { name: "Chaminé", url: "4/pt" },
    { name: "Interior da chaminé", url: "5/pt" },
    { name: "Sugar Bar - Área de embalamento de açúcar", url: "6/pt" },
    { name: "Fábrica Mágica", url: "7/pt" },
    { name: "Pintura de Deus ~ A tela viva da natureza", url: "8/pt" },
    { name: "Tanques de melaço - Altar de ossos de animais", url: "9/pt" },
    { name: "Tanques de melaço - Espaço de experiências infantis", url: "10/pt" },
    { name: "Tanques de melaço - Café Gubo", url: "11/pt" },
    { name: "Pavilhão do Chapéu Mágico e Colina Doce", url: "12/pt" },
    { name: "Palco das Engrenagens", url: "13/pt" },
    { name: "Casa da História de Cheluqian", url: "14/pt" },
    { name: "Fábrica de Tambores Qingxilin", url: "15/pt" },
    { name: "Casas de Banho Cana-de-Açúcar", url: "16/pt" },
    { name: "Rua del Arco-Íris Mágico", url: "17/pt" },
    { name: "Árvore da Vida - Passadiço Suspenso Skywalk", url: "18/pt" },
    { name: "Trono do Reino Mágico", url: "19/pt" },
    { name: "Teatro Sonho de Açúcar - Prensa de 5 níveis", url: "20/pt" },
    { name: "Livraria da Reparação", url: "21/pt" },
    { name: "Área de Passeio de Barco com Vara", url: "22/pt" },
    { name: "Tanque de cristalização ~ Máquina Gashapon de cristal de açúcar", url: "23/pt" },
    { name: "Misturador ~ Campo de tiro com arco coberto", url: "24/pt" },
    { name: "Casa Vermelha do Clarabóia e Locomotiva", url: "25/pt" },
    { name: "Balanço no Céu", url: "26/pt" },
    { name: "Área de caixotes de açúcar - Laser Tag de Aço", url: "27/pt" },
    { name: "A viagem de um grão de açúcar", url: "28/pt" },
    { name: "Pavilhão de Bênçãos ~ Templo Huangdi", url: "29/pt" }
  ]
};